apiVersion: v1
kind: Pod
metadata:
  name: buildah-kata
spec:
  containers:
    - name: buildah
      image: quay.io/buildah/stable:v1.30
      command: ["sh", "-c"]
      args:
      - sleep infinity
      volumeDevices:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: local-pvc
