apiVersion: v1
kind: Pod
metadata:
  name: echo-kata
  labels:
    app: echo-kata
  namespace: default
spec:
  containers:
    - name: echo-kata
      image: hashicorp/http-echo
      args: [ "-text", "Hello from Kata container", "-listen", ":8080"]
  runtimeClassName: kata-oc

---

kind: Service
apiVersion: v1
metadata:
  name: echo-kata-service
spec:
  selector:
    app: echo-kata
  ports:
    - port: 8080

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: echo-kata-route
spec:
  to:
    kind: Service
    name: echo-kata-service
  tls:
     termination: edge
