apiVersion: v1
kind: Pod
metadata:
  name: echo-runc
  labels:
    app: echo-runc
  namespace: default
spec:
  containers:
    - name: echo-runc
      image: hashicorp/http-echo
      args: [ "-text", "Hello from Runc container", "-listen", ":8080"]

---

kind: Service
apiVersion: v1
metadata:
  name: echo-runc-service
spec:
  selector:
    app: echo-runc
  ports:
    - port: 8080

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: echo-runc-route
spec:
  to:
    kind: Service
    name: echo-runc-service
  tls:
     termination: edge
